### ISSUE TITLE
Is CloudStack deprecated as a supported Cloud target type?

### ISSUE THREAD

**Issue by cairnsd** [usharesoft/appcenter-docs#347]
Apache CloudStack appears to be now missing from the supported Cloud [targets ](http://docs.usharesoft.com/projects/appcenter-user-guide/en/latest/pages/templating/supported-os.html)for generations.  Has this been deprecated ?

Apache CloudStack accepts Citrix Xenserver VHD ( Virtual Hard Disk ) or VMware ESX(i) OVA ( Open Virtual Architecture ) packaged up server files to be self uploaded ( each VHD or OVA  is a single server disk at a time during import....secondary, tertiary disks can be added later ).

IMPORT TYPES

OVA format for VMware = Open Virtualisation Architecture is a single file abiding to the DMTF (Distributed Management Task Force) standard which is really just a TAR’d  (Zipped) up server VMDK (Virtual Machine Disk File) which is a VMware Disk File (kept inside an OVA ) 

VHD for Citrix = Virtual Hard Disk is a Microsoft & Citrix Virtual Hard Disk  file type

Other Importable types ( with some PS work ) 

XVA =  Xen Virtual Appliance  is a TAR’d ( zipped  file ) which can be converted to an OVA to be imported into CloudPlatform ( Xenconverter 2.1 can convert an .xva into a .ovf and you can pick the disk file from within for single disk upload ) 
OVF = Open Virtualisation Architecture files abiding to the DMTF ( Distributed Management Task Force ) standard which is really just a package of a server which supports  with multiple disks

**Comment by emuus** [comment]
Cloudstack is in fact supported. It was mistakenly forgotten in the new table format. I have modified the table to list Cloudstack again.
