### ISSUE TITLE
Export appliance popin is not documented

### ISSUE THREAD

**Issue by segalaj** [usharesoft/appcenter-docs#370]
The export appliance popin RFE has been introduced in UForge 3.7-5.
It should be documented in the 3.7 branch of appcenter-docs

There are some pages affected:
- end-user/en/source/pages/templating/appliance-import-export.rst
- end-user/en/source/pages/migration/scan-to-appliance.rst

see #335

**Comment by emuus** [comment]
This is now covered in PR 373 (and 371 for changes in master)

**Comment by emuus** [comment]
Sorry, closed PR 373 as was pushed to wrong branch. Will redo PR.

**Comment by emuus** [comment]
Now in new PR 379. Sorry for the issues.

**Comment by segalaj** [comment]
Fixed by #379 
Thanks
