### ISSUE TITLE
CentOS 6 32bits is not supported by Fujitsu K5 cloud

### ISSUE THREAD

**Issue by segalaj** [usharesoft/appcenter-docs#900]
Hello,

The `Supported Machine Image Types` table in `end-user/en/source/pages/generating/supported-image-type.rst` is not up to date.
For instance `Cent OS 6 32bits` is not supported by Fujitsu K5 cloud.

Thanks

**Comment by emuus** [comment]
see PR https://github.com/usharesoft/appcenter-docs/pull/914
